/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import daos.alimentoDAO;
import entidades.alimento;
import javax.swing.JOptionPane;
import support.Formatacao;
import static support.Formatacao.isNumeric;
import support.Validacao;

/**
 *
 * @author Lucas
 */
public class IfrAlimento extends javax.swing.JInternalFrame {

    int codigo = 0;

    /**
     * Creates new form IfrAlimento
     */
    public IfrAlimento() {
        initComponents();
        //this.setLocationRelativeTo(jDesktopPanel);
        this.setTitle("Alimentos");
        Validacao.validarNumbersOnly(tfdCarboidrato, validarCarb);
        Validacao.validarNumbersOnly(tfdProteinas, validarProt);
        Validacao.validarNumbersOnly(tfdGorduras, validarGord);
        Validacao.validarNumbersOnly(tfdCalorias, validarCalorias);
        tfdCarboidrato.setText("0");
        tfdProteinas.setText("0");
        tfdGorduras.setText("0");
        tfdCalorias.setText("0");
        tfdNome.requestFocus();
        new alimentoDAO().popularTabela(tblAlimento, tfdCriterio.getText());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fechar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        tfdCarboidrato = new javax.swing.JFormattedTextField();
        tfdProteinas = new javax.swing.JFormattedTextField();
        tfdGorduras = new javax.swing.JFormattedTextField();
        tfdCalorias = new javax.swing.JFormattedTextField();
        validarCarb = new javax.swing.JLabel();
        validarProt = new javax.swing.JLabel();
        validarGord = new javax.swing.JLabel();
        validarCalorias = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfdCriterio = new javax.swing.JTextField();
        Pesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlimento = new javax.swing.JTable();
        Excluir = new javax.swing.JButton();
        Editar = new javax.swing.JButton();

        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do alimento*");

        jLabel2.setText("Proteínas por porção*");

        jLabel3.setText("Carboidratos por porção*");

        jLabel4.setText("Gorduras por porção*");

        jLabel5.setText("Calorias por porção*");

        tfdCarboidrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdCarboidratoKeyTyped(evt);
            }
        });

        tfdProteinas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdProteinasKeyTyped(evt);
            }
        });

        tfdGorduras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdGordurasKeyTyped(evt);
            }
        });

        tfdCalorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdCaloriasKeyTyped(evt);
            }
        });

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfdNome, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addComponent(tfdCarboidrato)
                        .addComponent(tfdProteinas)
                        .addComponent(tfdGorduras)
                        .addComponent(tfdCalorias)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(validarCarb, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(validarProt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(validarGord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(validarCalorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validarCarb, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfdCarboidrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validarProt, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfdProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validarGord, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tfdGorduras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validarCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel6.setText("Nome");

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        jScrollPane1.setAlignmentY(1.0F);

        tblAlimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Carboidratos", "Proteínas", "Gorduras", "Calorias", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlimento);

        Excluir.setText("Ativar / Desativar");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pesquisar)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Editar)
                .addGap(18, 18, 18)
                .addComponent(Excluir)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Editar)))
        );

        jTabbedPane1.addTab("Listagem", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Fechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fechar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        String valor = String.valueOf(tblAlimento.getValueAt(tblAlimento.getSelectedRow(), 0));

        alimento o = new alimentoDAO().consultarId(Integer.parseInt(valor));

        tfdNome.setText(o.getNome_alimento());
        System.out.println(o.getCarboidratos_por_porcao());
        System.out.println(o.getGorduras_por_porcao());
        
        tfdCarboidrato.setText(""+o.getCarboidratos_por_porcao());
        tfdProteinas.setText(""+o.getProteinas_por_porcao());
        tfdGorduras.setText(""+o.getGorduras_por_porcao());
        tfdCalorias.setText(""+o.getKcal_por_porcao());
        codigo = o.getId();

        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_EditarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed

        String entrada = tfdCarboidrato.getText();
        alimento alimento = new alimento();
        alimento.setNome_alimento(tfdNome.getText());
        alimento.setCarboidratos_por_porcao(Double.parseDouble(tfdCarboidrato.getText().replace(',','.')));
        alimento.setProteinas_por_porcao(Double.parseDouble(tfdProteinas.getText().replace(',','.')));
        alimento.setGorduras_por_porcao(Double.parseDouble(tfdGorduras.getText().replace(',','.')));
        alimento.setKcal_por_porcao(Double.parseDouble(tfdCalorias.getText().replace(',','.')));

        alimentoDAO alimentoDAO = new alimentoDAO();

        String retorno = null;

        if (tfdNome.getText().trim().isEmpty() == false
                && isNumeric(tfdCalorias.getText())
                && isNumeric(tfdProteinas.getText())
                && isNumeric(tfdGorduras.getText())
                && isNumeric(tfdCalorias.getText())) {

            if (codigo == 0) {
                retorno = alimentoDAO.salvar(alimento);
            } else {
                alimento.setId(codigo);
                retorno = alimentoDAO.atualizar(alimento);
            }
        }
        if (retorno == null && (tfdNome.getText().trim().isEmpty() == false
                && isNumeric(tfdCalorias.getText())
                && isNumeric(tfdProteinas.getText())
                && isNumeric(tfdGorduras.getText())
                && isNumeric(tfdCalorias.getText()))) {
            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");
            tfdNome.setText("");
            tfdCarboidrato.setText("0");
            tfdProteinas.setText("0");
            tfdGorduras.setText("0");
            tfdCalorias.setText("0");
            tfdNome.requestFocus();
            codigo = 0;
            new alimentoDAO().popularTabela(tblAlimento, tfdCriterio.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Problemas ao salvar registro! Verifique os dados informados\n\n"
                    + "Mensagem técnica:\n" + retorno);
        }


    }//GEN-LAST:event_SalvarActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        new alimentoDAO().popularTabela(tblAlimento, tfdCriterio.getText());
    }//GEN-LAST:event_PesquisarActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        String valor = String.valueOf(tblAlimento.getValueAt(tblAlimento.getSelectedRow(), 0));
        alimento a = new alimentoDAO().consultarId(Integer.parseInt(valor));
        codigo = a.getId();

        String retorno = new alimentoDAO().excluir(codigo);

        if (retorno == null) {
            JOptionPane.showMessageDialog(null, "Alterado com sucesso");
            new alimentoDAO().popularTabela(tblAlimento, "");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao alterar");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void tfdCarboidratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdCarboidratoKeyTyped
        Formatacao.forceDotsAndNumbers(evt);
    }//GEN-LAST:event_tfdCarboidratoKeyTyped

    private void tfdProteinasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdProteinasKeyTyped
        Formatacao.forceDotsAndNumbers(evt);
    }//GEN-LAST:event_tfdProteinasKeyTyped

    private void tfdGordurasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdGordurasKeyTyped
        Formatacao.forceDotsAndNumbers(evt);
    }//GEN-LAST:event_tfdGordurasKeyTyped

    private void tfdCaloriasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdCaloriasKeyTyped
        Formatacao.forceDotsAndNumbers(evt);
    }//GEN-LAST:event_tfdCaloriasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Fechar;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAlimento;
    private javax.swing.JFormattedTextField tfdCalorias;
    private javax.swing.JFormattedTextField tfdCarboidrato;
    private javax.swing.JTextField tfdCriterio;
    private javax.swing.JFormattedTextField tfdGorduras;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tfdProteinas;
    private javax.swing.JLabel validarCalorias;
    private javax.swing.JLabel validarCarb;
    private javax.swing.JLabel validarGord;
    private javax.swing.JLabel validarProt;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
